linkPrefix = "/doxity-simpleton"
name = "asf-contracts"
version = "1.0.0"
description = "Contracts for the AppStore Fundation"
buildTime = 2018-08-30T08:34:12.060Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
homepage = "https://AppStoreFoundation.github.io"

[interaction]